#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (C) 2011, Marine Biological Laboratory
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# Please read the COPYING file.
#

from pipeline.run import Run
from pipeline.sample import Sample
from pipeline.runconfig import RunConfig

if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description='Sequence Pipeline')
    parser.add_argument('-c', '--configuration', required=True, metavar = 'CONFIG_FILE', 
                                                 help = 'Configuration parameters of the run')

    args = parser.parse_args()

    run = Run(args.configuration)

    # do something with 'run'.
