#!/usr/local/www/vamps/software/python/bin/python
# -*- coding: utf-8 -*-

# Copyright (C) 2011, Marine Biological Laboratory
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# Please read the COPYING file.
#

import unittest
from   chimera import Chimera
import pipeline.utils as utils
import constants as C

# Chimeric denovo reads from env454:
# GNY988T01BTHV2
# GNY988T01EB1NH
# GNY988T01DPSMR
# GNY988T01EIW3U
# GNY988T01DRF01
# GNY988T01A1J76
# GNY988T01CHRHE
# GNY988T01CX70F
# GNY988T01BL036
# GNY988T01D358S
# 
# chimeric ref reads:
# GNY988T01AN8Z4
# GNY988T01CYYGD
# GNY988T01CEOD5
# GNY988T01EC49W
# GNY988T01EQB70
# GNY988T01B4BJA
# GNY988T01BF9OI
# GNY988T01E0F9N
# GNY988T01DKWFQ
# GNY988T01BDN7L
class unittestargs:
    def __init__(self):
        self.VERBOSE = False
        self.QUIET = False


class TestChimeraFunctions(unittest.TestCase):

    def setUp(self):
        """

        set up data used in the tests.

        setUp is called before each test function execution.

        """
        args = unittestargs()
        run = Run('./unittesting/unittest10.ini')
        
        
        # this not in env 454 (must have been altered)        
        self.id1 = 'GFADN4I02JYSXX' # fggre sdd  CHIMERA
        self.seq1 = 'TGGGCTGGGCGTAAAGGCGTAGGCGGATTTATAAGTCAGTGGTGAAAGCCTGCGGCTCAACCGTAGAATTGCCATTGATACTGTAGATCTTGAGTGC\
AATCGAGGTGGTTGGAATACGTAGTGTAGCGGTGAAATGCATAGATATTACGTAGAACACCAATTGCGAAGGCAGATCACTAGATTGTAACTGACGCTGA\
GGCACGAAAGCGTGGGGAGCGAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGGTGGGTGCTAGCTGTGGGCCACATTCCACGTGGTCCGTGAC\
GAAGTTAACACATTAAGCACCCCGCCTGGGGAGTACGGCCGCAAGGCTAAAACTCAAAGGAATTGACGGGGGCCCGCACAAGCGGCGGAGCATGCGGATT\
AATTCGATGCAACGCGAGGAACCTTACCAAGGCTTGACATATAGAGGAAAAGTGCAGAAATGCACTCCCCGCAAGGTCTCTATAC'
        self.chimera = Chimera('Bacterial','v6v4')

        # denovo chimera (trimmed)
        self.id2 = 'GNY988T01D358S'
        # AGATG   |       0 |               | 1064R-3     | -           | 
        # dist: CCGCGGTAATACGGAGGGTGCAAGCGTTAATCGGAATTAC |      0 |    480 | 
        # 20100917 | EQP-8-WC6 | KCK_EQP_Bv6v4 | v6v4   | 2010-09-20
        self.seq2 = 'TGGGCTAAAGCGCGCGTAGGTGGCTTGATAAGCCGGTTGTGAAAGCCCCGGGCTCAACCTGGGAACGGCATCCGGAACTGTCAAGCT\
AGAGTGCAGGAGAGGAAGGTAGAATTCCCGGTGTAGCGGTGAAATGCGTAGAGATCGGGAGGAATACCAGTGGCGAAGGCGGCCTTCTGGACTGACACTGA\
CACTGAGGTGCGAAAGCGTGGGTAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGTCGACCAGCCGTTGGGTGCCTAGCGCACTTTGTG\
GCGAAGTTAACGCGATAAGTCGACCGCCTGGGGAGTACGGCCGCAAGGTTAAAACTCAAAGGAATTGACGGGGGCCCGCACAAGCGGTGGAACATGTGGTTTA\
ATTCGATGCAACGCGAAGAACCTTACCTGGTCTTGACATCCTCGGACCGCTTCAGAGATGAAGTTTCCTCTTCGGAGGCCGAGTGAC'



        #ref chimera (trimmed)
        self.id3 = 'GNY988T01BDN7L'
        # AGATG   |       0 |               | 1064R-3     | -           | 
        # dist: CTGCGGTAATACGGAGGGTGCAAGCGTTAATCGGAAGTTAC |      0 |    482 | 
        # | 20100917 | EQP-8-WC6 | KCK_EQP_Bv6v4 | v6v4
        self.seq3 = 'TGGGCGTAAAGCGTGCGTAGGCGGTTTATTAAGTCAGATGTGAAAGCCCCGGGCTTAACCTGGGAACTGCATTTGAAACTGGTCAACTAGAGTATGGTA\
 GAGGAAAGTGGAATTTCTGGTGTAGCGGTGAAATGCGTAGATATCAGAAGGAAACATCAATGGCGAAGGCAGCTTTCTGGACCAATACTGACGCTGAGG\
 TACGAAAGCGTGGGTAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGATAACTAGCCGTTGGGGGGATTTACCCCTTAGTGGCGAAGC\
 TAACGCGTTAAGTTATCCGCCTGGGGAGTACGGCCGCAAGGCTAAAACTCAAAGGAATTGACGGGGACCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGA\
 TGCAACGCGAAGAACCTTACCTGGTCTTGACATCCTGCGAACTTTCTAGAAATAGATTGGTGCCTTCGGGAACGCAGTGAC'

 

    def test_chimera_ref(self):     
        pass
    
    def test_chimera_denovo(self):     
        pass
        
if __name__ == '__main__':
    #unittest.main()
    suite = unittest.TestLoader().loadTestsFromTestCase(TestChimeraFunctions)
    unittest.TextTestRunner(verbosity=2).run(suite)